const { createElement, Fragment, useState } = wp.element;
const { registerBlockType } = wp.blocks;
const { InspectorControls, useBlockProps, PanelColorSettings, RichText, URLInput } = wp.blockEditor;
const { PanelBody, SelectControl, RangeControl, ToggleControl, TextControl, Button, Modal } = wp.components;
const { __ } = wp.i18n;

// Import icons data (will be generated by build process)
const icons =
    window.weIconBlocksIcons ||
    window.webentwicklerinIcons ||
    {};

registerBlockType('webentwicklerin/icon', {
    edit: ({ attributes, setAttributes }) => {
        const {
            iconName,
            iconColor,
            backgroundColor,
            hoverIconColor,
            hoverBackgroundColor,
            width,
            height,
            linkUrl,
            linkTarget,
            linkRel,
            hasText,
            text,
            iconPosition,
            screenReaderOnly,
            gap,
            iconBorderWidth,
            iconBorderStyle,
            iconBorderColor,
            iconBorderRadius,
            hoverBorderColor,
            iconPadding,
            animation,
            animationStrength,
            animationRepeat,
        } = attributes;

        // Build inline styles
        const inlineStyles = {};

        // Set icon colors without touching surrounding text color
        if (iconColor) {
            inlineStyles['--icon-base-color'] = iconColor;
        }
        if (backgroundColor) {
            inlineStyles['--icon-background-color'] = backgroundColor;
        }
        if (hoverIconColor) {
            inlineStyles['--hover-icon-color'] = hoverIconColor;
        } else if (iconColor) {
            inlineStyles['--hover-icon-color'] = iconColor;
        }
        if (hoverBackgroundColor) {
            inlineStyles['--hover-bg-color'] = hoverBackgroundColor;
        } else if (backgroundColor) {
            inlineStyles['--hover-bg-color'] = backgroundColor;
        }

        // Apply gap on wrapper only when there is no link and a value is set
        if (!linkUrl && hasText && gap !== undefined && gap !== null && gap !== '') {
            inlineStyles.gap = gap;
        }

        // Icon size control
        if (width) {
            inlineStyles['--icon-width'] = width;
        }
        if (height) {
            inlineStyles['--icon-height'] = height;
        }

        // Icon padding & border are applied on the inner element, not on the wrapper.
        // We keep the CSS custom properties but scope them directly to `__inner`.

        // Animation controls: duration & iteration via CSS variables
        if (animation && animation !== 'none') {
            const strengthToDuration = {
                soft: '4s',
                normal: '2s',
                strong: '1s',
            };
            const duration = strengthToDuration[animationStrength] || strengthToDuration.normal;
            inlineStyles['--we-icon-animation-duration'] = duration;
            inlineStyles['--we-icon-animation-iterations'] = animationRepeat === 'once' ? '1' : 'infinite';
        }

        const blockProps = useBlockProps({
            style: inlineStyles,
            className: `icon-position-${iconPosition} ${hasText ? 'has-text' : 'no-text'} ${animation !== 'none' ? `icon-animation-${animation}` : ''}`
        });

        const getInnerStyles = () => {
            const styles = {
                width,
                height,
            };

            // Icon padding control (CSS var consumed in CSS for __inner)
            if (iconPadding !== undefined && iconPadding !== null) {
                styles['--icon-padding'] = iconPadding;
            }

            // Icon Border Styles (scoped CSS vars; avoid "border-*" substrings so WP globals don't match)
            if (iconBorderWidth) {
                styles['--we-icon-frame-width'] = iconBorderWidth;
            }
            if (iconBorderStyle) {
                styles['--we-icon-frame-style'] = iconBorderStyle;
            }
            if (iconBorderColor) {
                styles['--we-icon-frame-color'] = iconBorderColor;
            }
            if (iconBorderRadius) {
                styles['--we-icon-frame-radius'] = iconBorderRadius;
            }
            if (hoverBorderColor) {
                styles['--hover-border-color'] = hoverBorderColor;
            }

            return styles;
        };

        const iconOptions = Object.keys(icons).map(key => ({
            label: key.charAt(0).toUpperCase() + key.slice(1).replace('-', ' '),
            value: key
        }));

        // Icon Picker Modal Component
        const IconPickerModal = () => {
            const [isOpen, setIsOpen] = useState(false);
            const [searchTerm, setSearchTerm] = useState('');

            // Filter icons based on search term
            const filteredIcons = Object.keys(icons).filter(key =>
                key.toLowerCase().includes(searchTerm.toLowerCase())
            );

            const handleIconSelect = (iconKey) => {
                setAttributes({ iconName: iconKey });
                setIsOpen(false);
            };

            return (
                <Fragment>
                    <Button
                        onClick={() => setIsOpen(true)}
                        variant="secondary"
                        style={{ width: '100%', marginBottom: '10px' }}
                    >
                        {iconName ? (
                            <Fragment>
                                <span dangerouslySetInnerHTML={{ __html: icons[iconName] }}
                                    style={{
                                        width: '16px',
                                        height: '16px',
                                        marginRight: '8px',
                                        display: 'inline-flex',
                                        alignItems: 'center',
                                        justifyContent: 'center',
                                        overflow: 'hidden',
                                        flexShrink: 0
                                    }} />
                                {iconName.charAt(0).toUpperCase() + iconName.slice(1).replace('-', ' ')}
                            </Fragment>
                        ) : (
                            __('Select icon...', 'we-icon-blocks')
                        )}
                    </Button>

                    {isOpen && (
                        <Modal
                            title={__('Select icon', 'we-icon-blocks')}
                            onRequestClose={() => setIsOpen(false)}
                            className="webentwicklerin-icon-picker-modal"
                        >
                            <div style={{ marginBottom: '15px' }}>
                                <TextControl
                                    placeholder={__('Search icon...', 'we-icon-blocks')}
                                    value={searchTerm}
                                    onChange={setSearchTerm}
                                />
                            </div>

                            <div style={{
                                display: 'grid',
                                gridTemplateColumns: 'repeat(auto-fill, minmax(60px, 1fr))',
                                gap: '10px',
                                maxHeight: '400px',
                                overflowY: 'auto',
                                padding: '10px 0'
                            }}>
                                {filteredIcons.map(iconKey => (
                                    <button
                                        key={iconKey}
                                        onClick={() => handleIconSelect(iconKey)}
                                        style={{
                                            display: 'flex',
                                            flexDirection: 'column',
                                            alignItems: 'center',
                                            padding: '10px',
                                            border: iconName === iconKey ? '2px solid #007cba' : '1px solid #ddd',
                                            borderRadius: '4px',
                                            background: iconName === iconKey ? '#f0f8ff' : '#fff',
                                            cursor: 'pointer',
                                            transition: 'all 0.2s ease'
                                        }}
                                        onMouseEnter={(e) => {
                                            if (iconName !== iconKey) {
                                                e.target.style.borderColor = '#007cba';
                                                e.target.style.background = '#f8f9fa';
                                            }
                                        }}
                                        onMouseLeave={(e) => {
                                            if (iconName !== iconKey) {
                                                e.target.style.borderColor = '#ddd';
                                                e.target.style.background = '#fff';
                                            }
                                        }}
                                    >
                                        <span
                                            dangerouslySetInnerHTML={{ __html: icons[iconKey] }}
                                            style={{
                                                width: '24px',
                                                height: '24px',
                                                marginBottom: '5px',
                                                fill: '#333',
                                                display: 'flex',
                                                alignItems: 'center',
                                                justifyContent: 'center',
                                                overflow: 'hidden',
                                                flexShrink: 0
                                            }}
                                        />
                                        <small style={{
                                            fontSize: '10px',
                                            textAlign: 'center',
                                            color: '#666',
                                            wordBreak: 'break-all'
                                        }}>
                                            {iconKey.replace(/-/g, ' ')}
                                        </small>
                                    </button>
                                ))}
                            </div>
                        </Modal>
                    )}
                </Fragment>
            );
        };

        const currentIcon = icons[iconName] || '';

        return (
            <>
                <InspectorControls>
                    <PanelBody title={__('Icon Settings', 'we-icon-blocks')} initialOpen={true}>
                        <IconPickerModal />

                        <RangeControl
                            label={__('Width (px)', 'we-icon-blocks')}
                            value={parseInt(width)}
                            onChange={(value) => setAttributes({ width: value + 'px' })}
                            min={16}
                            max={200}
                        />

                        <RangeControl
                            label={__('Height (px)', 'we-icon-blocks')}
                            value={parseInt(height)}
                            onChange={(value) => setAttributes({ height: value + 'px' })}
                            min={16}
                            max={200}
                        />
                    </PanelBody>

                    <PanelBody title={__('Link & Text', 'we-icon-blocks')} initialOpen={false}>
                        <ToggleControl
                            label={__('Use as link', 'we-icon-blocks')}
                            checked={!!linkUrl}
                            onChange={() => setAttributes({ linkUrl: linkUrl ? '' : '#' })}
                        />

                        {linkUrl && (
                            <>
                                <TextControl
                                    label={__('Link URL', 'we-icon-blocks')}
                                    value={linkUrl}
                                    onChange={(value) => setAttributes({ linkUrl: value })}
                                    placeholder="https://..."
                                />

                                <SelectControl
                                    label={__('Open link in', 'we-icon-blocks')}
                                    value={linkTarget}
                                    options={[
                                        { label: __('Same window', 'we-icon-blocks'), value: '_self' },
                                        { label: __('New window', 'we-icon-blocks'), value: '_blank' },
                                    ]}
                                    onChange={(value) => setAttributes({
                                        linkTarget: value,
                                        linkRel: value === '_blank' ? 'noopener noreferrer' : ''
                                    })}
                                />
                            </>
                        )}

                        <ToggleControl
                            label={__('Show text', 'we-icon-blocks')}
                            checked={hasText}
                            onChange={(value) => setAttributes({ hasText: value })}
                        />

                        {hasText && (
                            <>
                                <TextControl
                                    label={__('Text', 'we-icon-blocks')}
                                    value={text}
                                    onChange={(value) => setAttributes({ text: value })}
                                />

                                <SelectControl
                                    label={__('Icon position', 'we-icon-blocks')}
                                    value={iconPosition}
                                    options={[
                                        { label: __('Left of text', 'we-icon-blocks'), value: 'left' },
                                        { label: __('Right of text', 'we-icon-blocks'), value: 'right' },
                                        { label: __('Above text', 'we-icon-blocks'), value: 'top' },
                                        { label: __('Below text', 'we-icon-blocks'), value: 'bottom' },
                                    ]}
                                    onChange={(value) => setAttributes({ iconPosition: value })}
                                />

                                <TextControl
                                    label={__('Gap between icon and text', 'we-icon-blocks')}
                                    value={gap}
                                    onChange={(value) => setAttributes({ gap: value })}
                                    placeholder="0.5em"
                                    help={__('e.g. 0.5em, 8px, 1rem', 'we-icon-blocks')}
                                />

                                <ToggleControl
                                    label={__('Text for screen readers only', 'we-icon-blocks')}
                                    checked={screenReaderOnly}
                                    onChange={(value) => setAttributes({ screenReaderOnly: value })}
                                />
                            </>
                        )}
                    </PanelBody>

                    <PanelColorSettings
                        title={__('Icon Colors', 'we-icon-blocks')}
                        colorSettings={[
                            {
                                value: iconColor,
                                onChange: (newColor) => setAttributes({ iconColor: newColor }),
                                label: __('Icon color', 'we-icon-blocks'),
                                enableAlpha: true,
                            },
                            {
                                value: hoverIconColor,
                                onChange: (newColor) => setAttributes({ hoverIconColor: newColor }),
                                label: __('Icon color on hover', 'we-icon-blocks'),
                                enableAlpha: true,
                            },
                        ]}
                    />

                    <PanelColorSettings
                        title={__('Background Colors', 'we-icon-blocks')}
                        colorSettings={[
                            {
                                value: backgroundColor,
                                onChange: (newColor) => setAttributes({ backgroundColor: newColor }),
                                label: __('Background', 'we-icon-blocks'),
                                enableAlpha: true,
                            },
                            {
                                value: hoverBackgroundColor,
                                onChange: (newColor) => setAttributes({ hoverBackgroundColor: newColor }),
                                label: __('Background on hover', 'we-icon-blocks'),
                                enableAlpha: true,
                            },
                        ]}
                    />

                    <PanelColorSettings
                        title={__('Border Colors', 'we-icon-blocks')}
                        colorSettings={[
                            {
                                value: iconBorderColor,
                                onChange: (newColor) => setAttributes({ iconBorderColor: newColor }),
                                label: __('Border color', 'we-icon-blocks'),
                                enableAlpha: true,
                            },
                            {
                                value: hoverBorderColor,
                                onChange: (newColor) => setAttributes({ hoverBorderColor: newColor }),
                                label: __('Border color on hover', 'we-icon-blocks'),
                                enableAlpha: true,
                            },
                        ]}
                    />

                    <PanelBody title={__('Icon Border', 'we-icon-blocks')} initialOpen={false}>
                        <RangeControl
                            label={__('Border Width', 'we-icon-blocks')}
                            value={parseInt(iconBorderWidth) || 0}
                            onChange={(value) => setAttributes({ iconBorderWidth: value + 'px' })}
                            min={0}
                            max={10}
                        />

                        <SelectControl
                            label={__('Border Style', 'we-icon-blocks')}
                            value={iconBorderStyle || 'solid'}
                            options={[
                                { label: __('Solid', 'we-icon-blocks'), value: 'solid' },
                                { label: __('Dashed', 'we-icon-blocks'), value: 'dashed' },
                                { label: __('Dotted', 'we-icon-blocks'), value: 'dotted' },
                                { label: __('None', 'we-icon-blocks'), value: 'none' },
                            ]}
                            onChange={(value) => setAttributes({ iconBorderStyle: value })}
                        />

                        <RangeControl
                            label={__('Border Radius (%)', 'we-icon-blocks')}
                            value={parseInt(iconBorderRadius) || 0}
                            onChange={(value) => setAttributes({ iconBorderRadius: value + '%' })}
                            min={0}
                            max={50}
                            step={1}
                            help={__('Border radius in percent (0–50%)', 'we-icon-blocks')}
                        />
                    </PanelBody>

                    <PanelBody title={__('Icon Padding', 'we-icon-blocks')} initialOpen={false}>
                        <RangeControl
                            label={__('Icon Padding (em)', 'we-icon-blocks')}
                            value={parseFloat(iconPadding) || 0.25}
                            onChange={(value) => setAttributes({ iconPadding: value === 0 ? '0' : value + 'em' })}
                            min={0}
                            max={15}
                            step={0.1}
                            help={__('Inner spacing around the icon (0–15em)', 'we-icon-blocks')}
                        />
                    </PanelBody>

                    <PanelBody title={__('Animation', 'we-icon-blocks')} initialOpen={false}>
                        <SelectControl
                            label={__('Animation Type', 'we-icon-blocks')}
                            value={animation}
                            options={[
                                { label: __('None', 'we-icon-blocks'), value: 'none' },
                                { label: __('Float Up', 'we-icon-blocks'), value: 'float-up' },
                                { label: __('Pulse', 'we-icon-blocks'), value: 'pulse' },
                                { label: __('Bounce', 'we-icon-blocks'), value: 'bounce' },
                                { label: __('Rotate', 'we-icon-blocks'), value: 'rotate' },
                                { label: __('Shake', 'we-icon-blocks'), value: 'shake' },
                            ]}
                            onChange={(value) => setAttributes({ animation: value })}
                            help={__('Select an animation for the icon', 'we-icon-blocks')}
                        />

                        {animation && animation !== 'none' && (
                            <>
                                <SelectControl
                                    label={__('Animation Strength', 'we-icon-blocks')}
                                    value={animationStrength || 'normal'}
                                    options={[
                                        { label: __('Soft', 'we-icon-blocks'), value: 'soft' },
                                        { label: __('Normal', 'we-icon-blocks'), value: 'normal' },
                                        { label: __('Strong', 'we-icon-blocks'), value: 'strong' },
                                    ]}
                                    onChange={(value) => setAttributes({ animationStrength: value })}
                                    help={__('Controls the animation speed/intensity', 'we-icon-blocks')}
                                />

                                <SelectControl
                                    label={__('Animation Repeat', 'we-icon-blocks')}
                                    value={animationRepeat || 'loop'}
                                    options={[
                                        { label: __('Loop continuously', 'we-icon-blocks'), value: 'loop' },
                                        { label: __('Play once', 'we-icon-blocks'), value: 'once' },
                                    ]}
                                    onChange={(value) => setAttributes({ animationRepeat: value })}
                                    help={__('Choose whether the animation runs once or loops', 'we-icon-blocks')}
                                />
                            </>
                        )}
                    </PanelBody>

                </InspectorControls>

                <div {...blockProps}>
                    {linkUrl ? (
                        <a
                            href={linkUrl}
                            target={linkTarget}
                            rel={linkTarget === '_blank' ? 'noopener noreferrer' : linkRel}
                            className="wp-block-webentwicklerin-icon__link"
                            style={hasText && gap !== undefined && gap !== null && gap !== '' ? { gap } : undefined}
                            aria-label={hasText && text ? `${text}` : `${iconName} icon`}
                        >
                            {iconPosition === 'top' && (
                                <div
                                    className="wp-block-webentwicklerin-icon__inner"
                                    style={getInnerStyles()}
                                    aria-hidden={hasText && text ? 'true' : undefined}
                                    dangerouslySetInnerHTML={{ __html: currentIcon }}
                                />
                            )}
                            {hasText && text && iconPosition === 'top' && (
                                <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                            )}
                            {(iconPosition === 'left' || iconPosition === 'right' || iconPosition === 'bottom') && (
                                <div
                                    className="wp-block-webentwicklerin-icon__inner"
                                    style={getInnerStyles()}
                                    aria-hidden={hasText && text ? 'true' : undefined}
                                    dangerouslySetInnerHTML={{ __html: currentIcon }}
                                />
                            )}
                            {hasText && text && iconPosition === 'bottom' && (
                                <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                            )}
                            {hasText && text && (iconPosition === 'left' || iconPosition === 'right') && (
                                <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                            )}
                        </a>
                    ) : (
                        <>
                            {iconPosition === 'top' && (
                                <div
                                    className="wp-block-webentwicklerin-icon__inner"
                                    style={getInnerStyles()}
                                    aria-hidden={hasText && text ? 'true' : undefined}
                                    dangerouslySetInnerHTML={{ __html: currentIcon }}
                                />
                            )}
                            {hasText && text && iconPosition === 'top' && (
                                <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                            )}
                            {(iconPosition === 'left' || iconPosition === 'right' || iconPosition === 'bottom') && (
                                <div
                                    className="wp-block-webentwicklerin-icon__inner"
                                    style={getInnerStyles()}
                                    aria-hidden={hasText && text ? 'true' : undefined}
                                    dangerouslySetInnerHTML={{ __html: currentIcon }}
                                />
                            )}
                            {hasText && text && iconPosition === 'bottom' && (
                                <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                            )}
                            {hasText && text && (iconPosition === 'left' || iconPosition === 'right') && (
                                <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                            )}
                        </>
                    )}
                </div>
            </>
        );
    },

    save: ({ attributes }) => {
        const {
            iconName,
            iconColor,
            backgroundColor,
            hoverIconColor,
            hoverBackgroundColor,
            width,
            height,
            linkUrl,
            linkTarget,
            linkRel,
            hasText,
            text,
            iconPosition,
            screenReaderOnly,
            gap,
            iconBorderWidth,
            iconBorderStyle,
            iconBorderColor,
            iconBorderRadius,
            hoverBorderColor,
            iconPadding,
            animation,
            animationStrength,
            animationRepeat,
        } = attributes;

        // Build inline styles for save (wrapper-level only: colors, sizes, layout)
        const inlineStyles = {};

        if (iconColor) {
            inlineStyles['--icon-base-color'] = iconColor;
        }
        if (backgroundColor) {
            inlineStyles['--icon-background-color'] = backgroundColor;
        }
        if (hoverIconColor) {
            inlineStyles['--hover-icon-color'] = hoverIconColor;
        } else if (iconColor) {
            inlineStyles['--hover-icon-color'] = iconColor;
        }
        if (hoverBackgroundColor) {
            inlineStyles['--hover-bg-color'] = hoverBackgroundColor;
        } else if (backgroundColor) {
            inlineStyles['--hover-bg-color'] = backgroundColor;
        }

        // Apply gap on wrapper only when there is no link and a value is set
        if (!linkUrl && hasText && gap !== undefined && gap !== null && gap !== '') {
            inlineStyles.gap = gap;
        }

        // Icon size control
        if (width) {
            inlineStyles['--icon-width'] = width;
        }
        if (height) {
            inlineStyles['--icon-height'] = height;
        }

        // Animation controls: duration & iteration via CSS variables
        if (animation && animation !== 'none') {
            const strengthToDuration = {
                soft: '4s',
                normal: '2s',
                strong: '1s',
            };
            const duration = strengthToDuration[animationStrength] || strengthToDuration.normal;
            inlineStyles['--we-icon-animation-duration'] = duration;
            inlineStyles['--we-icon-animation-iterations'] = animationRepeat === 'once' ? '1' : 'infinite';
        }

        const blockProps = useBlockProps.save({
            style: inlineStyles,
            className: `icon-position-${iconPosition} ${hasText ? 'has-text' : 'no-text'} ${animation !== 'none' ? `icon-animation-${animation}` : ''}`
        });

        const getInnerStyles = () => {
            const styles = {
                width,
                height,
            };

            // Icon padding control (CSS var consumed in CSS for __inner)
            if (iconPadding !== undefined && iconPadding !== null) {
                styles['--icon-padding'] = iconPadding;
            }

            // Icon Border Styles (scoped CSS vars; avoid "border-*" substrings so WP globals don't match)
            if (iconBorderWidth) {
                styles['--we-icon-frame-width'] = iconBorderWidth;
            }
            if (iconBorderStyle) {
                styles['--we-icon-frame-style'] = iconBorderStyle;
            }
            if (iconBorderColor) {
                styles['--we-icon-frame-color'] = iconBorderColor;
            }
            if (iconBorderRadius) {
                styles['--we-icon-frame-radius'] = iconBorderRadius;
            }
            if (hoverBorderColor) {
                styles['--hover-border-color'] = hoverBorderColor;
            }

            return styles;
        };

        const currentIcon = icons[iconName] || '';

        return (
            <div {...blockProps}>
                {linkUrl ? (
                    <a
                        href={linkUrl}
                        target={linkTarget}
                        rel={linkTarget === '_blank' ? 'noopener noreferrer' : linkRel}
                        className="wp-block-webentwicklerin-icon__link"
                        style={hasText && gap !== undefined && gap !== null && gap !== '' ? { gap } : undefined}
                        aria-label={hasText && text ? `${text} (${iconName})` : iconName}
                    >
                        {hasText && text && iconPosition === 'top' && (
                            <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                        )}
                        <div
                            className="wp-block-webentwicklerin-icon__inner"
                            style={getInnerStyles()}
                            aria-hidden={hasText && text ? 'true' : undefined}
                            dangerouslySetInnerHTML={{ __html: currentIcon }}
                        />
                        {hasText && text && iconPosition === 'bottom' && (
                            <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                        )}
                        {hasText && text && (iconPosition === 'left' || iconPosition === 'right') && (
                            <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                        )}
                    </a>
                ) : (
                    <>
                        {hasText && text && iconPosition === 'top' && (
                            <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                        )}
                        <div
                            className="wp-block-webentwicklerin-icon__inner"
                            style={getInnerStyles()}
                            aria-hidden={hasText && text ? 'true' : undefined}
                            dangerouslySetInnerHTML={{ __html: currentIcon }}
                        />
                        {hasText && text && iconPosition === 'bottom' && (
                            <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                        )}
                        {hasText && text && (iconPosition === 'left' || iconPosition === 'right') && (
                            <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                        )}
                    </>
                )}
            </div>
        );
    }
});

